server:
  port: 8012

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource.url: jdbc:mysql://localhost:3306/quanly_thuchi?autoReconnect=true
  datasource.username: root
  datasource.password: hoangtran2k

